language: ruby
cache: bundler
sudo: false
rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.6
  - 2.7
  - 3.0
  -
  - jruby-head
  - ruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
  fast_finish: true

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8229d26a4f90bcc6cd67
